// src/components/Todo.tsx
import { createSignal, For } from "solid-js";

export default function TodoSolid() {
    const [item, setItem] = createSignal<string>("");
    const [items, setItems] = createSignal<Array<string>>([]);
    const onSubmit = (e: Event) => {
        e.preventDefault();
        setItems([
            item(),
            ...items()
        ]);
        setItem("");
    };
    return <div class="card">
        <div class="card-header">
            <h5 className="card-title">
                SolidJS
            </h5>
            <form action="" onSubmit={onSubmit}>
                <input type="text" class="input" value={item()} onChange={(e) => setItem(e.target.value)} />
            </form>
        </div>
        <ul>
            <For each={items()}>
                {(singleItem) => <li class='todo-item'>{singleItem()}</li>}
            </For>
        </ul>
    </div>;
}

// src/components/Todo.svelte
<script>
let item = "";
let items = [];

const onSubmit = () => {
    items = [
        item,
        ...items
    ];
    item = "";
};

</script>

<div class="card">
    <div class="card-header">
        <h5 class="card-title">
            Svelte
        </h5>
        <form action="" on:submit|preventDefault={onSubmit}>
            <input type="text" class="input" bind:value={item}/>
        </form>
    </div>
    <ul>
        {#each items as singleItem}
            <li class='todo-item'>{singleItem}</li>
        {/each}
    </ul>
</div>
